spring:
  application:
    name: springbatch
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa: 
    hibernate:
      ddl-auto: create-drop
      show-sql: true
      properties:
        hibernate:
          format-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
server:
  port: 9090
csv:
  import:
    task:
      chunk:
        size: 1000
      executor:
        thread:
          size: 10